# -*- coding: utf-8 -*-
"""Classification_drug.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LDpB_HCA2uuTm_td6k_xXfLRjJ880-Fb

## Problem statement:

We have the patients data along with which drug is prescribed to him/her based on the features like:
1. Age
2. BP
3. Gender
4. Cholestrol
5. Na_to_K

Build a ML model to Predict which drug will a patient take based on the following features
1. Age - 32
2. BP - NORMAL
3. Gender - M
4. Cholestrol - HIGH
5. Na_to_K - 14.5

# 1.Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split

"""# Load The Dataset"""

df=pd.read_csv("/content/Drug_medicine.csv")

"""#Basic Datacheck"""

df.info()

df.shape

df.describe()

"""#Check for column with unique values

Comment: There is no col with unique values
"""

#check for null values
df.isnull().sum()

"""Comment:There are no null values"""

#check for duplicate rows
df.duplicated().sum()

"""Comment:There are no duplicate records in the dataset"""

#split data into categorical and numerical cols
cat=df.select_dtypes(include=["object"])
num=df.select_dtypes(exclude=["object"])

cat

num

#Check for any error values in dataset
for i in cat:
  print(df[i].value_counts())
  print("-----"*50)

"""Comment: There are no error values in a dataset

#check for outliers
"""

def detect_outlier(df,column):
  Q1=df[column].quantile(0.25)
  Q3=df[column].quantile(0.75)
  IQR=Q3-Q1
  lower_bound=Q1-1.5*IQR
  upper_bound=Q3+1.5*IQR
  return df[(df[column]>=lower_bound)&(df[column]<=upper_bound)]

for col in num:
  df_iqr=detect_outlier(df,col)

"""Comment: We called detect_outlier function for each numerical  column"""

print("Shape before outliers:",df.shape)
print("Shape after removing outliers:",df_iqr.shape)

"""Comment:There were 8 outliers and we removed it using Boxplot method."""



"""#Univariate Analysis"""

sns.histplot(df_iqr['Cholesterol'],bins=10)
plt.title("People with Cholesterol Risk")
plt.show()

"""Comment:There are nearly 100 people with high cholesterol risk and slightly less than 100 people with normal cholesterol. Difference is not huge.
The number of people with high cholesterol is almost equal to no of people with normal cholesterol.
"""

sns.histplot(df_iqr["BP"],bins=15)
plt.title("BP")
plt.show()

"""Comment:The largest group of people have high blood pressure.Second largest gruop of people have problem of low BP."""

sns.histplot(df_iqr["Na_to_K"],bins=10,kde=True)
plt.title("NA_TO_K Distribution")
plt.show()

"""Comment: The distributoin is Positive skewed.Most values cluster around  10.Many people have Na_to _K  level around this level.

#Bivariate Analysis
"""

cat

#Encoding
from sklearn.preprocessing import LabelEncoder

le_d={}

"""Comment: We  need to encode categorical col to numerical columns.le_d dictionary will be holding  the encodings for each categorical column ."""

for col in cat:
  le=LabelEncoder()
  df_iqr[col]=le.fit_transform(df_iqr[col])#It will convert  all categorical col to numerical
 # print(f"df_iqr[{col}]:",df_iqr[col])
  le_d[col]=le# asving the encoding for future use

le_d

df_iqr

"""# Bivariate analysis"""

sns.heatmap(df_iqr.corr(),annot=True)
plt.show()

"""Comment: Drug and Na_to_k has stongest correlation with coeff 0.6.It suggests that the sodium-to-potassium ratio is highly related to drug response.Second  highest coeff is 0.4 with Bp.
The Drug response variable is most strongly associated with Na_to_K and somewhat with BP.

#Model Building
"""

X=df_iqr.drop("Drug",axis=1)
y=df_iqr["Drug"]

X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=.7)

"""Comment:Divided data into train data to train the model and test data to test the model"""

#Importing multiple models
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

nb=GaussianNB()
rf=RandomForestClassifier()
dt=DecisionTreeClassifier()

"""Comment:Initialized the model"""

nb.fit(X_train,y_train)
rf.fit(X_train,y_train)
dt.fit(X_train,y_train)

"""Comment: Trained the model"""

#Model Evaluation
nb_pred=nb.predict(X_test)
rf_pred=rf.predict(X_test)
dt_pred=dt.predict(X_test)

"""Comment:Predicted the result using all  models."""

from sklearn import metrics

#Print Confusion matrix  for all models
print("Confusion matrix for Naive Bayes")
print(metrics.confusion_matrix(y_test,nb_pred))

print("Confusion matrix for Random Forest")
print(metrics.confusion_matrix(y_test,rf_pred))

print("Comfusion matrix for Decision Tree")
print(metrics.confusion_matrix(y_test,dt_pred))

nb_acc=metrics.accuracy_score(y_test,nb_pred)
rf_acc=metrics.accuracy_score(y_test,rf_pred)
dt_acc=metrics.accuracy_score(y_test,dt_pred)

"""Comment: Calculated accuracy score for each model so that we can decide the best model among these 3 models."""

print("Accuracy for Naive Bayes:",nb_acc)
print("Accuracy for Random Forest:",rf_acc)
print("accuracy for Decision Tree:",dt_acc)

"""Comment:Here best model is Decision tree but we will consider Random Forest as it is made up of multiple decision tree and it is slighly lower than  decision tree."""

best_model=rf

"""## Predict which drug will a patient take based on the following features
1. Age - 32
2. BP - NORMAL
3. Gender - M
4. Cholestrol - HIGH
5. Na_to_K - 14.5
"""

new_data=pd.DataFrame({'Age':[32],'Gender':['M'],'BP':['HIGH'],
                      'Cholesterol':['HIGH'],'Na_to_K':[14.5] })

new_data

"""Comment:Converted input features into dataframe format"""

new_data.info()

## Use the same encoding which we have saved and used to train our model in le_d

# Re-initialize new_data to ensure string types and correct BP value as per problem statement
new_data=pd.DataFrame({'Age':[32],'Gender':['M'],'BP':['NORMAL'],
                      'Cholesterol':['HIGH'],'Na_to_K':[14.5] })

new_data['Gender'] = le_d['Gender'].transform(new_data['Gender'])
new_data['BP'] = le_d['BP'].transform(new_data['BP'])
new_data['Cholesterol'] = le_d['Cholesterol'].transform(new_data['Cholesterol'])

new_data

#pass this input to best model
prediction=best_model.predict(new_data)

prediction

#inverse transform to get the final output
print(le_d['Drug'].inverse_transform(prediction))

